numero1 = float(input("ingrese el primer numero:"))
numero2 = float(input("ingrese el segundo numero:"))
numero3 = float(input("ingrese el tercer numero:"))
numero4 = float(input("ingrese el cuarto numero:"))
numero5 = float(input("ingrese el quinto numero:"))
promedio = ((numero1+numero2+numero3+numero4+numero5)/5)
print("el promedio es:",promedio)